#ENC[AES256_GCM,data:ggbOfBBNUPh8yNQqNpXN064TrNqg9GvYSMVvBjO3Lvagc/ASZ8iOiwaE3746jD2epCE+20TddAgOlkS7+XXifg==,iv:frizEsCIbSO0J0pNiD8OfwtzkuRsUTZBpco0KzM6uls=,tag:V4lD+ibpctpoIk9OMeurjQ==,type:comment]
#ENC[AES256_GCM,data:lTI3aMNRqZD3ge5sVM3BYQencJQt06l2rCqkauz61XpirROnE/FBChfo3gq5QlVx2mgNKVdU,iv:rfU4c5alJbqVUfrl59Qke7wKn4gHuSFi8CtfBDFyCIo=,tag:6qrQbk22m0EwAxhvWJ/GeA==,type:comment]
#ENC[AES256_GCM,data:qX23dg8iK/pzMhB0VVmnAY96S6PvW4b5yJsp2VITA9Ccb40DpK9X46PvgIRHAronxkVyt3m3Y2vj,iv:PUNRXDkbrAKkwGMwb1rAzRUTlA3J8eeNrH3XSCsLmiU=,tag:XnA0qBYaUsYaUvzKdFwZUw==,type:comment]
#
#ENC[AES256_GCM,data:ZXe1dQBjsQgceCs=,iv:I6SAC7H0s8qN2/mzxp4oUj2yJgVAoLECd7MDlYy1fRI=,tag:ylWyyZmzwbTLu7OKc+Z7qQ==,type:comment]
#ENC[AES256_GCM,data:vRrBgfl7uCvsoYnWBLTyrT8z/OwluC821OxK1wTjc+24arlA,iv:+sw0yDdGMWOu6NgYroA0p2JTRQMyV2j7ftHnHG5SKLA=,tag:eSR5WQbVd85WC4OhKFzdRA==,type:comment]
#ENC[AES256_GCM,data:+i0kHR30R0JfmyfV9zIZHTpdQRCh7rLJfNR4I4ulmL2+S4hHNNAOB/Eefa37jPztKLBe8FCROkNqWDYH9g==,iv:epxx3YNwuQXoFh5YsIIWGoAprfr1Jsy9izoVBd63Rfs=,tag:+gyIy8DBeRSPEoM226hjgA==,type:comment]
#ENC[AES256_GCM,data:JDBwZZw2wZBh2bHkFNZENt0z+3vebMhTKda5OBix8x4TfDoFU1pWHDfT4ZoYHjotvFzwK0WkxV3d734X/2M=,iv:7bg/7U+bBkqUyE0VD9012vwPJeS8wHtkQ2xeaVgOUDw=,tag:bmPFp//9j97UoE5BthCpbA==,type:comment]
apiVersion: ENC[AES256_GCM,data:gHQ=,iv:d9iBrdY+9JBsfsti+wF72Km1Cb2yJP8fjHC2k1QeeMI=,tag:pbGlCUfxBt6zm6yQqQTpdQ==,type:str]
kind: ENC[AES256_GCM,data:2++3PRZy,iv:Q6poAxMjISAZWCTX65rpd/tnDumGJy+/PUZkawKBCuo=,tag:v8Ojb4uTxCXQWWmdX7s3yw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RUKgAcMRxFk89rtCbfvwaQlVgChllJU=,iv:yWPJcCBTqlkJ5ozh5BN5k9XDlRPyZnkdf2FTlP2DbwQ=,tag:osc46YwwiU3vmfcE4kamLw==,type:str]
    namespace: ENC[AES256_GCM,data:bcpJaRi+eg==,iv:82lja8OByDwjXetD6fxhV3Msa2g3oTHdO6vcGqTR0VQ=,tag:FGsDgCqBiRDHpRE6yVaJwg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:mKVopKpcCg==,iv:fFaUybetNODc53O+YEBoLgvqPnU3DfcyProuSVngLbQ=,tag:bcbJ2K4tH1iHJC0l5Lp3Sg==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:MBykR4LKCg==,iv:p8JywlReI2Iqo3lE735ikfdDx7I38+cAoAmxYAEd+bo=,tag:lF2Ln0nZ61sPk1yxb6tccQ==,type:str]
type: ENC[AES256_GCM,data:3ea3nvfF,iv:yjt3PEPMZvRKIhXnsUmtDWUQ3zk07HxlfNawn1qCM3U=,tag:uBcm3RLzlPW4Ziqp3xrzBw==,type:str]
stringData:
    OVH_ENDPOINT: ENC[AES256_GCM,data:R5SCkKv+,iv:SiFbrce+EsQGlcxE5rXDOSHGwrkeP1dwjsigZml3TTM=,tag:3DMDZe7dVKjpUXMEuJuA3g==,type:str]
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:2G9NfMCc1n1qte27iBFAVg==,iv:mbuEgMm+vkFC6j8WUEl2XbGuV7IFJssuiXQiZPuuUyk=,tag:AG7IesTYQo9IU73tkBiHJQ==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:iAQH03FDTBZEH6vpMbZssQzR7k8PVfG6E4IjyzXSwgw=,iv:Ymd+1mAlhRD2HPIQJA/akK837bZQR8cM82GqKup2TTM=,tag:4wyHC5nRzpq0n6jSmtxN6w==,type:str]
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:u/VKCrbBKDjUYDGkqXdROaBA4Ztm1hRja6hqlXh6iuw=,iv:6/sBrCjw6DMo/eyKnvPp1p39WLcFiFOR4/aDrerEv/E=,tag:t8TNkrf/PQ7j/cTennw+0Q==,type:str]
sops:
    age:
        - recipient: age1s34wy4nl56s4at7u63y7djms0629x65ddqtvvk2v97q05nza4g0shzyfjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdnI1MVJxT1JTeGtpL3dr
            eGNxQmExdU9HRlhRZGFPU0xwNkxZemdhNzI4Ckl5Y05RblEvNXcyZFUrR2JKbjVV
            SmVtUiszMStORGpJVUFLM3BtaWxOb2MKLS0tIEVlVWVpSXpVdFN2N0J5UTlNT3l2
            V09JL21FY0NLZm1mcVRGcWwwZGdwT0kKvFO8Eq9lnUn3yG11LIjgKsOedu4Qq/wd
            P0dYNp2cWenAe69gy70q/DqGO1QWvxqejyT7RyC0/yJjaotKG97X3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T14:00:06Z"
    mac: ENC[AES256_GCM,data:O7uOrWuV8kvo7f4Wq4DiMRCNYa5I6mVHzlS9t/ajv8xZ3FcX+MsscJmh5LzpyOA5KhY1KvtvNiwprJw4k1ujrYk3PWhWizGBWgSeKYpoijiZBCDc37IRE7AXhYhtGp1ZIhhwWj7ZXscdT1szJYm/x7cf+uUupmvRgK4kll7BEGc=,iv:2J4RO1N9W5sPYLkMYYZ1GApclAvOHLO9aOkqAJMpc2M=,tag:8GIQDQIMXmA7aDHuwzl8YQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
