[Interface]
Address    = 10.200.0.2/24
PrivateKey = iGBZk7TD65rKLzW3DefBxqqeFS6En0m8q5MOjjT/pEo=

[Peer]
# VPS worker-2
PublicKey           = 9kUZes4UvLCzYplEZj8AuV1nPc7gVcc/LdL/XYHYiEI=
Endpoint            = 163.172.181.187:51820
AllowedIPs          = 10.200.0.1/32, 10.201.0.0/24
PersistentKeepalive = 25
