#ENC[AES256_GCM,data:Lsj9n4vEtcwqz7tMlmehHemwKwf1U4Gskl1sKtIgs+Bj092KnjrLyPvqxAxWb9BaFLHyYAUzwQ==,iv:aaxjOdGdOcASVtTCML3C4PRsNv3ryCegAcajMtCt+1U=,tag:G7e8oc0wTScJxAaKLvL/Bw==,type:comment]
#
#ENC[AES256_GCM,data:pxOQx6ubOmlnnbzenCyN/RA2bc6uzTVBtfWu4JpgLAugtzyOru8gRegLLSLYD0Q6GXIwh5Y=,iv:s9InkNqOaavgfDAR9nAfzZcOHE9oTNknDpvYz1YqZzI=,tag:f8zzGsQRh2pA05qmZ1z9Mg==,type:comment]
#ENC[AES256_GCM,data:eYMMcYNXIu72/0Y=,iv:jW93HS2sDkb8ZdyyKxyJkUPwJTQBfR4xePpc755ElyI=,tag:wjUU+1o0fZ1MtSpLJQNkUQ==,type:comment]
#ENC[AES256_GCM,data:j3Y37ccaelo57ZptIckASHfUMcvdY6SxjM8kBI+LVzQxEyKC,iv:B9PNk2xPJR7f9H+4Z3qV20BSkh81ODqyQE2Sxe98fQY=,tag:0OJnbfE0N2oYbJpAlxo9Zw==,type:comment]
#ENC[AES256_GCM,data:Y7N79IHHpnx0gbQFRZ1OfRd+7fPmp7S+DhtJFfZRBXY5jgBl7bWzL46dQz9Qt7jOcmNVGyoVOV2Q+hyrvTVHLA==,iv:YSScH7Sbu3hflbDscI4Hn1SxBI94VLRXDOnZBNJB40s=,tag:IjT5GyOE7u144Gk63d1WPg==,type:comment]
#ENC[AES256_GCM,data:K60u7j8r/AfBSq+stOqFKv31KcjQGV74ME4oxCXU/Km84KeUgOGwkgbw,iv:2rURkJ5j1siA+KfQ/AA4F2y4fOtjDu/LxiSEOB8H7sE=,tag:9WDMaYrS+pD/9VZxrtJi5w==,type:comment]
#ENC[AES256_GCM,data:4pguYqUwYWw9vwCGqmK9NPpuOB+pb1fYJVDhUva/l/i+CmSZwRvcnpuTwmoo6XAHjmN8xdwcf/SC0LuKSwwYWz8DuA==,iv:PY+Ftc9soP+6ZXirSyTcloKjEoaSNE8PURJu4frRRDU=,tag:yHEAJsinoFbwyRaWD5OZEQ==,type:comment]
#
#ENC[AES256_GCM,data:mGLukiZ6ERxsRqcNlVGP74O1QbzykeP+bDHosN3UkEiVqPIDN3kV7kZkRYovdWNKwYP9bYB3KQlUYfSAsEdM9Xmof0E0obi2eycPjsHkjGUWK9w=,iv:uw8IX6Jk/l3s46vXE5D7K79Lyo9LhjGWLFl2dbAwBts=,tag:ov0uiOTQTfrxQVXSZMvi/Q==,type:comment]
#ENC[AES256_GCM,data:RNKq3LNx5lO9brvjq7GsPVcUqIQ/+tzs7PG+/GE/cq3qRc2YqtctRPihLC6iewuK3AGfFhBPKQHx9W/hqm5k9CQOFD5jqdDvKMX6FlsFyg4frBLNlSzu,iv:7ZGFJaRRi5qNK+GKHBiOsbq1xdLiWbFy6eMBwuXZ9dE=,tag:FcJqrINgDj+7k8UMECbSCA==,type:comment]
apiVersion: ENC[AES256_GCM,data:i74=,iv:wUFZv0sL1GkH/Q1GXivrDE0r77rAJXlehAPF5q3aXfE=,tag:q8uGUbIENi98oDXMiMdHTw==,type:str]
kind: ENC[AES256_GCM,data:iT7TLSwh,iv:QiQ8tg3PwhVN7EIOwacvxw7Zk+02h+o13hA4aEzf95o=,tag:X0ya06llcZAWZzrfFaS/Gw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:U8bFUbnx3K5nG9I3z4whFg==,iv:PF3yP1WICP8N8Q+I7FXxR4lPzWVv9OCmadYDtQx5NWw=,tag:Y8FmxYc1owlD7lztuKcWjA==,type:str]
    namespace: ENC[AES256_GCM,data:s0Zjyi5vERI=,iv:mXgUYNdNAvGSHSQWQ5+LM4qmePvqqGJMsGNUQ60LFeE=,tag:sDhnB7ZSD/STc4nzbUYjfg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:ru0N2VDZ1EQ=,iv:OC8us5UjfpkiGHpzs6YQNwZfrUGAqEcIZ3RRaz17XCs=,tag:WBtgSew7XtdL2eTX1Wjxvw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:i+5hxW1ApQ==,iv:YVYFYrukOOlOmKnW1/1SJP8TjWX5cQxPTZUWcnYtGgk=,tag:d+XayZs/wuDSkj8am+xFdA==,type:str]
type: ENC[AES256_GCM,data:0zrvSI3E,iv:dOxTGbT2o/OzYEwm4PbGD4p3rTdJkltJVNbG60y7mEw=,tag:hwMhNvkN3Cy+puMNRnaedQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:VIEreRZN5ZzBAv6VNOPfD+1UB5sxfvdSPB5EA85xpPwAnc5dlw74qF7X02NM9zz4YLzJvtIdSTxAAxZzgMzjRrMJhQSrBQz76fX9h5oEmVyAeMK/9+7tmaA=,iv:m2kXZkBz02rOGvkcTN7QJnSBbbdcVGeYWofP36yrAwM=,tag:fHwIT1GPVFmYe2PY7PEeXQ==,type:comment]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:KPlQ/znwWAcb,iv:Mip6WYrh6KBaS4txU79TmikO8Z6fzVICfqGgJE3/a6Q=,tag:UP0Heujm8r7Xz38+onpJCA==,type:str]
    #
#ENC[AES256_GCM,data:3k3IXosJwWpv3egCUjQHDkf3izSiFa3f9Ga0Z/21CHk=,iv:zPciFQ3hEMILNjvhXhNXpbA3QBJOc9r9XDVlVfz48Vg=,tag:VARcftHvM6bmsEldMj7o3Q==,type:comment]
#ENC[AES256_GCM,data:K4/XD4WL4QnU6MRBrQR4NBMnQI8QqnsdEO+w0ew=,iv:KY/yTZop493GLW8It+06VVKtgqBN9J6KtyL4otqVZH8=,tag:7iF6TqxH5HJWMxmLqioWZg==,type:comment]
#ENC[AES256_GCM,data:Bua9cH/35yymx8j7G3RKlFxSNX0JR5dawByHQneMqdgQ,iv:YMsxEy3RcLRpFYOLwO25eCSAyb0r/xsPZm6vkSiR6kA=,tag:5bt5Ov3NrvCRLxSHbQ12Pw==,type:comment]
#ENC[AES256_GCM,data:KS+XTyMRwemChbubG5udeANszXkUVnQrlynS,iv:bmDFMhe6BCYpQug+dvzOOzNC1UmedaeCyWSahnJ0rac=,tag:Pmb1/UiEtQP6n0dt8e9bSg==,type:comment]
sops:
    age:
        - recipient: age1s34wy4nl56s4at7u63y7djms0629x65ddqtvvk2v97q05nza4g0shzyfjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdmFUTysxaTRwVHQ0dmpm
            aUMzU0IzRDE3ekdKczJpYVE5ZW1LMUFiSURnCmI5M1NWdXZxSW9DcXNHVHJ0Z05y
            NG9Edk9kRDRMSmhOUGdONWxRemxuM28KLS0tIEF1YTFUcngrN0FFWXVKc0p2VXpX
            ODlITW54czd2VEpKeGpTMFkwa1hKZjgKEwsjz1wKRAB9VQWcwOwesKfyyVkcC4/U
            pqij+ccw8pnH1HGubWOxEjGIl5Vz0STjtZreG/VZEqNlHl+DH/UH7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T23:12:02Z"
    mac: ENC[AES256_GCM,data:li+NzI/ZLEke475N6JvuddGN/RSgWqOxZLBsL2mJkNnH5eP67EFvofF2kfkUjkkzifE2pzhU8H4Ym4FJ0s7U66AOYV1t+y5/FSGtTvVmfNBZXC5ilnjzfZwRDPyZSbGDGCdMENR2Dbd7M9bW67HoBHSfJaJ5ogj1Orh9A2pMr3I=,iv:lytJAbi3FNTXue3FNmUUPjwhkf9O6+xL7FXJfK4krQs=,tag:rhx4jnI/4SjRxVSmpHcPXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
