#ENC[AES256_GCM,data:lr2YPxLOh2zJ8ezaPpdIa4Qhx92/VWKSylTXA4PBrpKG+dSRqQxtRTJs1mY/sZ94zaz0G3LoYQ==,iv:IqFSU9IxG+E/JPeUlV+TtL9g4+IxkTmwNf4FpXrPrmU=,tag:0LbHjj14TIEQzgj85MtTKg==,type:comment]
#
#ENC[AES256_GCM,data:xF1/SI8Ro7LWl6c9gmqrOYeP1ljfo/e27mPeK9DIt7gYae32/wK2DOJc5RYPsZmSdcs2w/A=,iv:QNLNGtZ8uXJT2DhviEgo5mKnf2kaxTbqdy7vNeEPdCQ=,tag:w1g1p9Q9pU3DHKFpT2Hfiw==,type:comment]
#ENC[AES256_GCM,data:j1ZNVJaIscGLUyk=,iv:zXy8a16K/C1C5Jyk6h3PjXAiow5pnVWkG7OG9GS4oEk=,tag:WBuPwYlaD58jRz0u6fqb5Q==,type:comment]
#ENC[AES256_GCM,data:LFcjDxxqlQIM1G8m5f4swBY/dE9bTLoN55g29vF+ijshJNtz,iv:RrLgs7cafjrTd6jdJNfN0NIJQXeHE1tWoIG93Rx45R8=,tag:on9R3aImcbAJoqMfxfnZOQ==,type:comment]
#ENC[AES256_GCM,data:f0M1FNl6XQZ2mUwSaZMp6huskEHuoifrjZKF9thkmjDAF/yiYJa0kAQVTT69i4GJEQiNykHQ61tpDbL/fH6Qig==,iv:IKsRr3o1iQxbbNXlIelZfN5l9P0cm4gQZQ1OF7Zjy6U=,tag:VIUx7ENdGjFkj5dCgwDQMg==,type:comment]
#ENC[AES256_GCM,data:zNzgV5ce/Ei2GU+Ql5Hxm3g1PhskfCTAi+j1NrYLktPb1ZpHWml4+Mlk,iv:ryBdyXYDOX1iapbGmqmitMPK9svozG0XBXDn3YbDQUk=,tag:IW7hOgp9WRxVbJgDCz890w==,type:comment]
#ENC[AES256_GCM,data:Bf8g8NusGwqRm1ho004NT4K3I94RgGj3LnKDFtwf9PlpqvhnmVp7FMrE98AvQ5va8QO+W7z6HwGx1l/fnPGot99DDQ==,iv:I9Dh1BvlfRstBF973xd4Q2eQCvP6O1zsZOkxgOoMg2M=,tag:mP63ja3GybKOAv+2EF9Iiw==,type:comment]
#
#ENC[AES256_GCM,data:etoN1oygf1OFvODgMmgSx8S+MGGWG8b4LtZ4vIrgT05y7lqqC17/2lJzw2Q8ZvpELJzXzEZ4GGMODvNB6o8hFKle9cIKC5pNwlYZK3WzImQRwPs=,iv:q/io3UsGv/gK4mPrtt4/Mhfc+l8nalDuHRdXyWJlIfQ=,tag:kYkwyTIhAM3Pny/RbsWVOA==,type:comment]
#ENC[AES256_GCM,data:RPaXTK1YrPg/7WxXj+h/nHQB6JfOJJaVmDQq/tfQ2P0xE3mPmF7nrR0VaJnpZrofZUbt+JB7Crc31RuzpqfWEriTQIF3oz58TkGguM1ILSzJ2+jrSltg,iv:oWu9erNLn4hBuo8Km9zbouyhaG9IoSZa6Kw2weAzxmY=,tag:HRAx1E9Dbr8g9VobQnXgRA==,type:comment]
apiVersion: ENC[AES256_GCM,data:kcI=,iv:YojKr+S2DEg8EAq/OKeBvx5UjqwUjQZcMaMunX1uWGU=,tag:y8Oep6G/LEgMpgudlZZ6OA==,type:str]
kind: ENC[AES256_GCM,data:xLIyIE95,iv:WpMQ/TpGM3qDe5XqNnAk+TIQwgRr974YzRF6iYyGCj0=,tag:cOsMFiOWV3IM7eR3aPmfCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Vrv//A/e0RksBSGsUq+KYw==,iv:H4ul/OwdV++s0hKZ7Nu8f5lWat30/7LlfidO4DXkK1c=,tag:eMx72aB+p+qvkUP3bcWkWA==,type:str]
    namespace: ENC[AES256_GCM,data:4yPXu/Mjuj4=,iv:Uo5zzqAt/T3F8FKJl6lugUnYdsqghKvu8JOrExl8s1o=,tag:WojJ0Y1dJvWSgK3vgbH5uA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:yhOFXWaXsxk=,iv:SVPbObjPuFYIUfUzLOWWO6SfcRBFixLoODfKk8ma8ds=,tag:BREzxIf4jC3Bu9qJPPMGaQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:BYLnAnN+GA==,iv:HO/LtGOTyngZjeg25JaC3jLUxgpR7nyKmdaH3G3dRPI=,tag:4PnRwHa+4uG0DM7POvwnZw==,type:str]
type: ENC[AES256_GCM,data:DkRWQOH0,iv:DYqo0Pq1Un2Exp8EXas0AwFoFITn5FU+jPzrRDq5DZk=,tag:crPI8rLWcGDV4lED/eVELQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:BQD4acQGspL8QyoPJ1jWb0GPhmTcR7mLvV2+5LHc3lXfmR+Nqyjfy0qAkTxjB+HeSBJ8bCy6S+tGxNdA/5oCBrRrjpMBVTYCkNWMuKpdKYupgVV+60LsJAI=,iv:KY9mN4ozHXGAjRksr0TJj2TuNtEXz4FCpNmzlztX9ek=,tag:o43Yj2x3aTqaB3u66Hk+NQ==,type:comment]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:kTkI66xNoaGQrMjmTQG2BpdT9gG2xJG73wXKljTeS/s=,iv:J7SXK0HZSgOYzbaLHIqsqmOk5iys3PsN4nnmqTaQnW8=,tag:cO38QhY0D+Sa+wQ2mTmGlg==,type:str]
    #
#ENC[AES256_GCM,data:ywDFJrOnZN/f9vVz5A3SuExvBZeoA0JD2YrgAsd6Bpk=,iv:3DkionHHVVSeDYPorxALrUZDPfKDtjSn9B5QB9mh76k=,tag:dt78AK8Dp5ckyGa6ofd2sw==,type:comment]
#ENC[AES256_GCM,data:wIL3acQBhmaWT29OMAqf9r3IHEGUipXYZxp7a50=,iv:Jkkd6O75dx0AXv9wHurRrbEk5c0QnKU0qvlYUHzUTtY=,tag:n6H7D/mm7BRdcVSXyEr5aw==,type:comment]
#ENC[AES256_GCM,data:G8qCfC5tQhI/3BcuXNLB1uC6WCDb7Lb6JRMxS5z43ari,iv:VUwEtktkBpUI68StqzX9L0veCtQxp6dmgK1YWQf2qmA=,tag:Oto1TqZN/RYwzHMtg1CRvQ==,type:comment]
#ENC[AES256_GCM,data:l/i7zSrdc7mbhOgjLacVZ+7B13RRHRYREFok,iv:Hzvv8fnhfJaQRaorIO6BhhhmtIYdO07B79B4GLy0kzo=,tag:dfmiW06tDHXgTm3GIHYNLg==,type:comment]
sops:
    age:
        - recipient: age1s34wy4nl56s4at7u63y7djms0629x65ddqtvvk2v97q05nza4g0shzyfjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVmIxNGdLcEVrU000R3N4
            UGRYSW5YMElLYlZWQ29Td2RMV2RENTRocFFvCjl1dUJ5bHlBMEZraGNzZUNpTktq
            azJSMUtuTVROR3RiSStJck9aUTZIdUUKLS0tIGp1Nk9KYVV4bnhYKzZzTng2SGlL
            WjQrVnNXU3JCbTdBWkZZa0o4K2VZdE0KlDG5W5JkITV/X+WjuehICBa8ybkzSC9x
            VFwekfAz2ogy83eY6rhSXDO6ZyN1G498qnDHiu/F3HvKZvn06b0QGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T16:56:05Z"
    mac: ENC[AES256_GCM,data:PXzRTLXtX9QduUpDLpAzO81zLQy3yyoxO3OfUYHEvoBGMO5HRr4vRgCq5pPhUSHpJ0fAmSCCO70zI0aNlkmNn2WNmAGG7bJFq89omdWxTXvW/NFP1xt3oUBP5e3dfwpc/8WgAIh6XTi0pw+ji0iDpdWHzartGQD75pKLZp2S8Dk=,iv:6eetOrTSKvJdI1MilXzyAVWxDsgIwfrGPDax6uYxVQU=,tag:/m0ZE/1AlaTNHC16mH0wqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
