[Interface]
Address    = 10.200.0.2/32
PrivateKey = aGi9nBzM0ljLkl/ek/iNqco8mjLfdjfNzjbEmi2Dr2c=
DNS        = 1.1.1.1

[Peer]
# worker-1 Scaleway — serveur WireGuard NAS tunnel (wg1)
PublicKey           = K+ZLiS6B7KQZVupHqR60ciSIvFNKt4W3qZdxzKtnskk=
Endpoint            = 51.158.107.191:51821
AllowedIPs          = 10.200.0.0/24
PersistentKeepalive = 25
